# See: https://golangci-lint.run/docs/configuration/file/
version: "2"

linters:
  enable:
    # Defaults
    - govet
    - staticcheck
    - errcheck
    - unused
    # Additional
    - gosec
    - bidichk
    - errorlint
    - bodyclose
    - unconvert
    - usestdlibvars
    - modernize
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
  settings:
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - os.Setenv
        - os.Unsetenv
    unused:
      parameters-are-used: false

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/23prime/claude-launcher

run:
  timeout: 5m
  modules-download-mode: readonly
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
